### ISSUE TITLE
Many waitForStatusRecordUnlock crash, thread lock

### ISSUE THREAD

**Issue by PoissonBallon** [immobiliare/RealHTTP#57]
### Bug Report

| Q                   | A      |
| ------------------- | ------ |
| BC Break            | no |
| Version             | 1.6.2  |

#### Summary

We have many (but intermittent) `waitForStatusRecordUnlock` crash and we doesn't know why, 

Do you have any idea ? Misuse of the HTTPClient ? 

Thanks for ur helping,

<img width="1718" alt="Screenshot 2022-07-26 at 17 14 44" src="https://user-images.githubusercontent.com/8491808/181045145-cd9ab83c-7afe-4476-8bde-6a21065426a1.png">

**Comment by malcommac** [comment]
Did you have a replicable project?  
I'm looking at the code and I think we can avoid the async operation of serialization just because it's already inside the async `fetch()` operation.

Moreover, looking [on swift forums](https://forums.swift.org/t/weird-crash-with-concurrency/59411) I've also seen it could be a compiler error fixed in Swift 5.7.
